### PR TITLE
Add few use cases about the playone

### PR DESCRIPTION
**Pull request by pokk**
as the title.

Waiting for the #71

### CODE REVIEW

**Comment by pokk** [comment]
@lekaha 

After the #71 is merged, Please take a look this. Thanks!

**Comment by lekaha** [comment]
I just add `WIP` and waiting for #71

**Comment by pokk** [comment]
@lekaha 

#71 was merged. Please take a look. Thanks!

**Comment by lekaha** [comment]
Merge first but the change is too big..

**Pull request merged**
